spring.application.name=api

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/medcare_api}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root@1}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.port=8080
server.error.include-stacktrace=never

spring.main.allow-bean-definition-overriding=true
